### ISSUE TITLE
Wrong labels of Tox21 dataset

### ISSUE THREAD

**Issue by lei-liu1** [CurryTang/TSGFM#3]
Hello,

I found there are some problems with the labels in Tox21 dataset. There are `nan` and more than one `1` values  in the one-hot labels. This issue can be reproduced  by the following code:
``` 
from subgcon.efficient_dataset import GraphSubgraphDataset
dataset = GraphSubgraphDataset('tox21', 'args.sb', 'args.tag_data_path', num_classes=12, few_shot=False)
print(dataset.dataset[7820].y)
```
I downloaded the data from this link [https://huggingface.co/datasets/zkchen/tsgfm/blob/main/minilmdata.zip](url).

**Comment by CurryTang** [comment]
Hi, moleculeNet dataset do have nan labels. The label is not one-hot but multiple binary values. You need to filter those abnormal values

**Comment by lei-liu1** [comment]
Thank you for the clarification!
